# Generated by Django 5.0.7 on 2024-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updates_date',
            field=models.DateTimeField(null=True),
        ),
    ]
