# Generated by Django 5.0.7 on 2024-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_updates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updates_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
