# Generated by Django 5.0.7 on 2024-07-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_room_created_date_alter_room_updates_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='content',
            new_name='Description',
        ),
    ]
