# Generated by Django 5.0.7 on 2024-08-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updates_date', 'created_date']},
        ),
    ]
